name: Prueba de Scripts Python

on: [push]

jobs:
  prueba-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r codigos/requirements.txt 

    - name: Ejecutar pruebas
      run: |
        errores=""
        for archivo in codigos/*.py; do
          if ! python "$archivo"; then
            echo "Error en $archivo"
            errores="$errores $archivo"
          fi
        done

        if [ -n "$errores" ]; then
          echo "Hubo errores en los siguientes scripts: $errores. Corrige los errores antes de hacer push."
          exit 1
        fi
